"""Add image_filename to Sighting model

Revision ID: 1e3c8d316c83
Revises: 823817407b00
Create Date: 2025-10-23 09:20:30.502409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3c8d316c83'
down_revision = '823817407b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
