"""Add state column to Sighting model

Revision ID: 823817407b00
Revises: 
Create Date: 2025-10-10 14:27:35.439741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823817407b00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False, server_default='NY'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
